const translation = {
    "global_name": "Argentum",
    "global_error_offline": "server offline.",
    "level": "Level",
    "warrior": "Warrior",
    "wizard": "Wizard",
    "ullathorpe": "Ullathorpe",
    "nix": "Nix",
    "connect_username": "Username",
    "connect_password": "Password",
    "connect_create_button": "Create",
    "connect_enter_button": "Enter",
    "connect_error_empty_fields": "you must complete all the fields to enter your account.",
    "connect_error_username_characters": "username must have a minimum of 4 characters and a maximum of 20.",
    "connect_error_password_characters": "password must have a minimum of 6 characters and a maximum of 18.",
    "connect_error_password_mismatch": "password doesn't match this account.",
    "connect_error_unknown": "unknown error, please contact support.",
    "connect_error_user_already_connected": "user is already online.",
    "create_account_title": "Create new account",
    "create_account_username": "Username:",
    "create_account_email": "Email:",
    "create_account_password": "Password:",
    "create_account_repeat_password": "Repeat password:",
    "create_account_tos_one": "I accept the",
    "create_account_tos_two": "of",
    "create_account_tandc": "terms and conditions",
    "create_account_create_button": "Create account",
    "create_account_error_empty_fields": "you must complete all the fields and accept the terms and conditions to create an account.",
    "create_account_error_username_characters": "username must have a minimum of 4 characters and a maximum of 20.",
    "create_account_error_password_mismatch": "passwords must match.",
    "create_account_error_password_characters": "password must have a minimum of 6 characters and a maximum of 18.",
    "create_account_error_tos_not_accepted": "you must accept the terms and conditions to create an account.",
    "create_account_error_invalid_email": "invalid email address, try with a different one.",
    "create_account_error_username_taken": "this username already exists please use another one.",
    "account_character_list": "Characters list",
    "account_delete_character": "Delete character",
    "account_are_you_sure": "Are you sure to delete the character",
    "account_enter_password": "Enter your password to delete your character:",
    "account_confirm_button": "Delete my character",
    "account_enter_character_button": "Enter the game",
    "account_create_new_character_button": "Create new character",
    "account_delete_character_button": "Delete character",
    "account_logout_button": "Log out",
    "account_error_empty_fields": "you need to enter your password to delete a character."
}

export default translation;