const translation = {
    "global_name": "Argentum",
    "global_error_offline": "servidor offline.",
    "level": "Nivel",
    "male": "Hombre",
    "female": "Mujer",
    "human": "Humano",
    "elf": "Elfo",
    "darkelf": "Elfo Oscuro",
    "dwarf": "Enano",
    "gnome": "Gnomo",
    "mage": "Mago",
    "cleric": "Clérigo",
    "warrior": "Guerrero",
    "assassin": "Asesino",
    "thief": "Ladrón",
    "bard": "Bardo",
    "druid": "Druida",
    "bandit": "Bandido",
    "paladin": "Paladín",
    "hunter": "Cazador",
    "fisher": "Pescador",
    "blacksmith": "Herrero",
    "lumberjack": "Talador",
    "miner": "Minero",
    "carpenter": "Carpintero",
    "pirat": "Pirata",
    "strength": "Fuerza",
    "agility": "Agilidad",
    "intelligence": "Inteligencia",
    "charisma": "Carisma",
    "constitution": "Constitución",
    "ullathorpe": "Ullathorpe",
    "nix": "Nix",
    "connect_username": "Usuario",
    "connect_password": "Contraseña",
    "connect_create_button": "Crear",
    "connect_enter_button": "Entrar",
    "connect_error_empty_fields": "debes completar todos los campos para ingresar a tu cuenta.",
    "connect_error_username_characters": "el nombre de usuario debe contener un mínimo de 4 caracteres y hasta un máximo de 20.",
    "connect_error_password_characters": "la contraseña debe contener un mínimo de 6 caracteres y hasta un máximo de 18.",
    "connect_error_password_mismatch": "la contraseña no coincide con la de esta cuenta.",
    "connect_error_unknown": "error desconocido, póngase en contacto con soporte.",
    "connect_error_user_already_connected": "el usuario ya se encuentra conectado.",
    "create_account_title": "Crear nueva cuenta",
    "create_account_username": "Usuario:",
    "create_account_email": "Email:",
    "create_account_password": "Contraseña:",
    "create_account_repeat_password": "Repetir contraseña:",
    "create_account_tos_one": "Acepto los",
    "create_account_tos_two": "de",
    "create_account_tandc": "términos y condiciones",
    "create_account_create_button": "Crear cuenta",
    "create_account_error_empty_fields": "debes completar todos los campos y aceptar los términos y condiciones para crear una cuenta.",
    "create_account_error_username_characters": "el nombre de usuario debe contener un mínimo de 4 caracteres y hasta un máximo de 20.",
    "create_account_error_password_mismatch": "las contraseñas deben coincidir.",
    "create_account_error_password_characters": "la contraseña debe contener un mínimo de 6 caracteres y hasta un máximo de 18.",
    "create_account_error_tos_not_accepted": "debes aceptar los términos y condiciones para crear una cuenta.",
    "create_account_error_invalid_email": "dirección de email inválida, prueba con otra.",
    "create_account_error_username_taken": "ya existe un usuario con ese nombre, utiliza otro nombre por favor.",
    "account_character_list": "Lista de personajes",
    "account_delete_character": "Borrar personaje",
    "account_are_you_sure": "Estás seguro de borrar el personaje",
    "account_enter_password": "Ingresa tu contraseña para borrar el personaje:",
    "account_confirm_button": "Borrar mi personaje",
    "account_enter_character_button": "Ingresar al juego",
    "account_create_new_character_button": "Crear nuevo personaje",
    "account_delete_character_button": "Borrar personaje",
    "account_logout_button": "Cerrar sesión",
    "account_error_empty_fields": "debes ingresar tu contraseña para eliminar el personaje.",
    "character_create_title": "Creación de personaje",
    "character_create_name": "Escribe el nombre de tu nuevo personaje:",
    "character_create_gender": "Selecciona tu Género",
    "character_create_race": "Selecciona tu Raza",
    "character_create_class": "Selecciona tu Clase",
    "character_create_attributes": "Atributos",
    "character_create_back": "Volver",
    "character_create_throwdices": "Tirar dados",
    "character_create_next": "Crear personaje",
    "character_create_empty_name": "debes introducir un nombre para crear tu nuevo personaje.",
    "character_create_empty_gender": "debes seleccionar el género de tu personaje.",
    "character_create_empty_race": "debes seleccionar la raza de tu personaje.",
    "character_create_empty_class": "debes seleccionar la clase de tu personaje."
}

export default translation;